name: main

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validation
        run: |
          value=$(cat integration/prd/DEMO2/values.json | jq .value | cut -d '"' -f 2) # <--- SET YOUR PATH HERE
          echo "Parsed value: $value"
          if [[ "$value" == "success" ]]; then
            exit 0
          else
            echo "::error title=validation-error::not allowed value: $value"
            exit 1
          fi
